services:
    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        environment:
            - MYSQL_DATABASE=sgs
            - MYSQL_USER=sgs
            - MYSQL_PASSWORD=123456
            - MYSQL_RANDOM_ROOT_PASSWORD="yes"
        volumes:
            - ./data/mysql:/var/lib/mysql

    
        # healthcheck: # check the healthiness with the following configuration
        #   test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '--user=sgs', '--password=123456']
        #   # test: "/etc/init.d/mysql status"
        #   interval: 3s
        #   # timeout: 3s
        #   retries: 5

    # nginx:
    #   # image: nginx:alpine
    #   build: nginx/
    #   ports:
    #     - 80:80
    #   # volumes:
    #   #   - /home/docker-nginx/nginx.conf:/etc/nginx/nginx.conf
    #     # - ./webgl:/webgl
    #   #   - /home/docker-nginx/log:/var/log/nginx
    #     # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    #   #   - /home/docker-nginx/html:/usr/share/nginx/html

    # api:
    #     build: api/
    #     restart: 'always'
    #     ports:
    #         - 8080:8080
    #     depends_on:
    #         - mysql

    # room:
    #     build: service-room/
    #     restart: always
    #     ports:
    #         - 5001:5001
    #         - 5002:5002
