apiVersion: v1
kind: Service
metadata:
  name: room-service
spec:
  selector:
    app: room
  ports:
  - protocol: TCP
    port: 5002
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: room-deployment
spec: 
  selector: 
    matchLabels: 
      app: room
  replicas: 3
  template:
    metadata:
      labels:
        app: room
    spec: 
      containers:
      - name: room
        image: 127.0.0.1:5009/service-room
        ports:
        - containerPort: 5001
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: config-map