apiVersion: v1
kind: Service
metadata:
  name: room-grpc-service
spec:
  selector:
    app: room
  ports:
  - protocol: TCP
    port: 5002
---
apiVersion: v1
kind: Service
metadata:
  name: room-signalr-service
spec:
  # type: NodePort
  selector:
    app: room
  ports:
  - protocol: TCP
    port: 5001
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: room
spec: 
  selector: 
    matchLabels: 
      app: room
  replicas: 1
  template:
    metadata:
      labels:
        app: room
    spec: 
      containers:
      - name: room
        image: room
        imagePullPolicy: Never
        ports:
        - containerPort: 5001
        - containerPort: 5002
        envFrom:
        - configMapRef:
            name: config-map