apiVersion: v1
kind: Service
metadata:
  name: api-service
spec:
  # type: NodePort
  selector:
    app: api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: api
spec: 
  selector: 
    matchLabels: 
      app: api
  replicas: 3
  template:
    metadata:
      labels:
        app: api
    spec: 
      containers:
      - name: api
        image: api
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: config-map